// Auto-generated by build.py — do not edit manually
// Generated: 2026-02-16T19:07:32.857855
window.__DATA__ = {
  "generatedAt": "2026-02-16T19:07:32.857855",
  "openingDate": "2025-12-18",
  "daysSinceLaunch": 60,
  "numUnits": 6,
  "summary": {
    "totalBookings": 186,
    "totalGross": 184673,
    "totalToOwner": 166783,
    "blendedAdr": 513,
    "ownerMargin": 90.3,
    "otaPct": 8.9,
    "avgStay": 1.9,
    "avgLeadTime": 38,
    "totalNights": 360,
    "totalExpenses": 39334,
    "otaBookingPct": 89.8,
    "directBookings": 10,
    "repeatGuestPct": 1.6,
    "costPerTurn": 115
  },
  "monthlyData": [
    {
      "month": "Dec '25",
      "gross": 22695,
      "toOwner": 20483,
      "bookings": 24,
      "adr": 582
    },
    {
      "month": "Jan '26",
      "gross": 40041,
      "toOwner": 35785,
      "bookings": 56,
      "adr": 393
    },
    {
      "month": "Feb '26",
      "gross": 46609,
      "toOwner": 42082,
      "bookings": 47,
      "adr": 536
    },
    {
      "month": "Mar '26",
      "gross": 31055,
      "toOwner": 28475,
      "bookings": 22,
      "adr": 501
    },
    {
      "month": "Apr '26",
      "gross": 16486,
      "toOwner": 14615,
      "bookings": 14,
      "adr": 717
    },
    {
      "month": "May '26",
      "gross": 10217,
      "toOwner": 9315,
      "bookings": 10,
      "adr": 601
    },
    {
      "month": "Jun '26",
      "gross": 9551,
      "toOwner": 8961,
      "bookings": 6,
      "adr": 637
    },
    {
      "month": "Jul '26",
      "gross": 2602,
      "toOwner": 2254,
      "bookings": 2,
      "adr": 650
    },
    {
      "month": "Aug '26",
      "gross": 1249,
      "toOwner": 1213,
      "bookings": 1,
      "adr": 625
    },
    {
      "month": "Oct '26",
      "gross": 1688,
      "toOwner": 1458,
      "bookings": 2,
      "adr": 422
    },
    {
      "month": "Nov '26",
      "gross": 1204,
      "toOwner": 1041,
      "bookings": 1,
      "adr": 602
    },
    {
      "month": "Dec '26",
      "gross": 1275,
      "toOwner": 1102,
      "bookings": 1,
      "adr": 425
    }
  ],
  "sourceData": [
    {
      "name": "Airbnb",
      "bookings": 106,
      "pct": 57.0,
      "revenue": 101304
    },
    {
      "name": "Expedia",
      "bookings": 37,
      "pct": 19.9,
      "revenue": 33521
    },
    {
      "name": "Booking.com",
      "bookings": 24,
      "pct": 12.9,
      "revenue": 17350
    },
    {
      "name": "Direct",
      "bookings": 10,
      "pct": 5.4,
      "revenue": 8975
    },
    {
      "name": "ZenStay",
      "bookings": 7,
      "pct": 3.8,
      "revenue": 5356
    },
    {
      "name": "VHR",
      "bookings": 1,
      "pct": 0.5,
      "revenue": 278
    },
    {
      "name": "owner",
      "bookings": 1,
      "pct": 0.5,
      "revenue": 0
    }
  ],
  "unitData": [
    {
      "unit": "1",
      "bookings": 34,
      "toOwner": 34168,
      "avgRev": 1005,
      "adr": 429,
      "nights": 86,
      "avgStay": 2.5
    },
    {
      "unit": "2",
      "bookings": 25,
      "toOwner": 29390,
      "avgRev": 1176,
      "adr": 802,
      "nights": 40,
      "avgStay": 1.6
    },
    {
      "unit": "3",
      "bookings": 24,
      "toOwner": 17746,
      "avgRev": 739,
      "adr": 466,
      "nights": 42,
      "avgStay": 1.8
    },
    {
      "unit": "4",
      "bookings": 31,
      "toOwner": 23272,
      "avgRev": 751,
      "adr": 435,
      "nights": 58,
      "avgStay": 1.9
    },
    {
      "unit": "5",
      "bookings": 43,
      "toOwner": 38376,
      "avgRev": 892,
      "adr": 529,
      "nights": 83,
      "avgStay": 1.9
    },
    {
      "unit": "6",
      "bookings": 29,
      "toOwner": 23831,
      "avgRev": 822,
      "adr": 528,
      "nights": 51,
      "avgStay": 1.8
    }
  ],
  "expenseCategories": [
    {
      "category": "Cleaning",
      "amount": 11543,
      "pct": 29.3
    },
    {
      "category": "Supplies",
      "amount": 10495,
      "pct": 26.7
    },
    {
      "category": "Taxes & Licenses",
      "amount": 7388,
      "pct": 18.8
    },
    {
      "category": "CapEx",
      "amount": 5959,
      "pct": 15.2
    },
    {
      "category": "Marketing",
      "amount": 2410,
      "pct": 6.1
    },
    {
      "category": "Maintenance",
      "amount": 852,
      "pct": 2.2
    },
    {
      "category": "Other",
      "amount": 687,
      "pct": 1.7
    }
  ],
  "expenseMonthly": [
    {
      "month": "Dec '25",
      "total": 8713,
      "cleaning": 0,
      "supplies": 5505,
      "capex": 2928,
      "maint": 280,
      "marketing": 0,
      "other": 0
    },
    {
      "month": "Jan '26",
      "total": 21454,
      "cleaning": 8483,
      "supplies": 4918,
      "capex": 2966,
      "maint": 572,
      "marketing": 2410,
      "other": 2105
    },
    {
      "month": "Feb '26",
      "total": 9167,
      "cleaning": 3060,
      "supplies": 72,
      "capex": 66,
      "maint": 0,
      "marketing": 0,
      "other": 5970
    }
  ],
  "topVendors": [
    {
      "vendor": "Spring Cleaning (Quentin & Kayli Keiser)",
      "amount": 11543,
      "category": "Cleaning"
    },
    {
      "vendor": "City of Santa Barbara (Business License Tax Application)",
      "amount": 7388,
      "category": "Taxes & Licenses"
    },
    {
      "vendor": "Amazon",
      "amount": 6421,
      "category": "Supplies"
    },
    {
      "vendor": "MAJESTIC METALS (Majestic Metals)",
      "amount": 2738,
      "category": "CapEx"
    },
    {
      "vendor": "Tripadvisor",
      "amount": 2400,
      "category": "Marketing"
    },
    {
      "vendor": "Skiview Productions (Juan C Lopez Romero)",
      "amount": 2175,
      "category": "CapEx"
    },
    {
      "vendor": "Costco",
      "amount": 2087,
      "category": "Supplies"
    },
    {
      "vendor": "Public Goods",
      "amount": 1140,
      "category": "Supplies"
    },
    {
      "vendor": "California Design Den",
      "amount": 1052,
      "category": "Supplies"
    },
    {
      "vendor": "Martin Hernandez Painting",
      "amount": 832,
      "category": "CapEx"
    }
  ],
  "sbCompData": [
    {
      "metric": "ADR",
      "casaYano": 513,
      "sbMedian": 321,
      "sbTop25": 521
    },
    {
      "metric": "Owner Margin",
      "casaYano": 90.3,
      "sbMedian": 75,
      "sbTop25": 85
    },
    {
      "metric": "OTA Commission %",
      "casaYano": 8.9,
      "sbMedian": 15,
      "sbTop25": 12
    }
  ],
  "proForma": {
    "monthly": [
      {
        "month": "Jan",
        "adr": 375,
        "occ": 82,
        "gross": 67350,
        "netOwner": 56076,
        "opex": 9500,
        "noi": 46576,
        "bookings": 57
      },
      {
        "month": "Feb",
        "adr": 400,
        "occ": 80,
        "gross": 62350,
        "netOwner": 51829,
        "opex": 6870,
        "noi": 44959,
        "bookings": 50
      },
      {
        "month": "Mar",
        "adr": 425,
        "occ": 78,
        "gross": 71075,
        "netOwner": 58995,
        "opex": 7314,
        "noi": 51681,
        "bookings": 54
      },
      {
        "month": "Apr",
        "adr": 425,
        "occ": 80,
        "gross": 70475,
        "netOwner": 58481,
        "opex": 7203,
        "noi": 51278,
        "bookings": 53
      },
      {
        "month": "May",
        "adr": 450,
        "occ": 78,
        "gross": 74700,
        "netOwner": 61923,
        "opex": 7314,
        "noi": 54609,
        "bookings": 54
      },
      {
        "month": "Jun",
        "adr": 525,
        "occ": 85,
        "gross": 90300,
        "netOwner": 74615,
        "opex": 7647,
        "noi": 66968,
        "bookings": 57
      },
      {
        "month": "Jul",
        "adr": 550,
        "occ": 85,
        "gross": 97225,
        "netOwner": 80267,
        "opex": 7869,
        "noi": 72398,
        "bookings": 59
      },
      {
        "month": "Aug",
        "adr": 525,
        "occ": 82,
        "gross": 90300,
        "netOwner": 74615,
        "opex": 7647,
        "noi": 66968,
        "bookings": 57
      },
      {
        "month": "Sep",
        "adr": 350,
        "occ": 72,
        "gross": 53900,
        "netOwner": 44947,
        "opex": 6648,
        "noi": 38299,
        "bookings": 48
      },
      {
        "month": "Oct",
        "adr": 350,
        "occ": 70,
        "gross": 53900,
        "netOwner": 44947,
        "opex": 6648,
        "noi": 38299,
        "bookings": 48
      },
      {
        "month": "Nov",
        "adr": 375,
        "occ": 75,
        "gross": 59375,
        "netOwner": 49428,
        "opex": 6870,
        "noi": 42558,
        "bookings": 50
      },
      {
        "month": "Dec",
        "adr": 375,
        "occ": 80,
        "gross": 65500,
        "netOwner": 54522,
        "opex": 7425,
        "noi": 47097,
        "bookings": 55
      }
    ],
    "waterfall": [
      {
        "name": "Gross Revenue",
        "value": 856450,
        "type": "positive"
      },
      {
        "name": "OTA Commissions",
        "value": -76224,
        "type": "negative"
      },
      {
        "name": "Taxes (TOT)",
        "value": -102774,
        "type": "negative"
      },
      {
        "name": "Processing",
        "value": -21411,
        "type": "negative"
      },
      {
        "name": "Net to Owner",
        "value": 656041,
        "type": "subtotal"
      },
      {
        "name": "Cleaning",
        "value": -78430,
        "type": "opex"
      },
      {
        "name": "Supplies/Maint",
        "value": -12454,
        "type": "opex"
      },
      {
        "name": "Other OpEx",
        "value": -2669,
        "type": "opex"
      },
      {
        "name": "Mgmt Fee (10%)",
        "value": -85645,
        "type": "mgmt"
      },
      {
        "name": "Property Tax",
        "value": -26679,
        "type": "opex"
      },
      {
        "name": "Insurance",
        "value": -13500,
        "type": "opex"
      },
      {
        "name": "Other Fixed (6 items)",
        "value": -24000,
        "type": "opex"
      },
      {
        "name": "NOI (excl. remaining TBD)",
        "value": 412664,
        "type": "total"
      }
    ],
    "gross": 856450,
    "netOwner": 656041,
    "opex": 93553,
    "mgmtFee": 85645,
    "propertyTax": 26679,
    "insurance": 13500,
    "otherFixed": 24000,
    "noiBeforeFixed": 562488,
    "noiAfterKnown": 412664,
    "avgOcc": 78.9,
    "avgAdr": 513,
    "mgmtFeePct": 0.1
  },
  "config": {
    "mgmtFeePct": 0.1,
    "propertyTaxAnnual": 26679,
    "insuranceAnnual": 13500,
    "sbMedianAdr": 321,
    "sbTop25Adr": 521
  }
};
