// Auto-generated by build.py — do not edit manually
// Generated: 2026-03-09T14:39:47.353184
window.__DATA__ = {
  "generatedAt": "2026-03-09T14:39:47.353184",
  "openingDate": "2025-12-18",
  "daysSinceLaunch": 81,
  "numUnits": 6,
  "summary": {
    "totalBookings": 255,
    "totalGross": 272709,
    "totalToOwner": 243798,
    "blendedAdr": 394,
    "ownerMargin": 89.4,
    "otaPct": 10.1,
    "avgStay": 2.7,
    "avgLeadTime": 43,
    "totalNights": 693,
    "totalExpenses": 48900,
    "otaBookingPct": 94.9,
    "directBookings": 13,
    "repeatGuestPct": 0,
    "costPerTurn": 87,
    "totalOccupancy": 77.6,
    "blendedRevPar": 276
  },
  "monthlyData": [
    {
      "month": "Dec '25",
      "gross": 22695,
      "toOwner": 20483,
      "bookings": 24,
      "adr": 405,
      "nights": 56,
      "occupancy": 66.7,
      "revpar": 270
    },
    {
      "month": "Jan '26",
      "gross": 40041,
      "toOwner": 35785,
      "bookings": 56,
      "adr": 286,
      "nights": 140,
      "occupancy": 75.3,
      "revpar": 215
    },
    {
      "month": "Feb '26",
      "gross": 54065,
      "toOwner": 48880,
      "bookings": 55,
      "adr": 398,
      "nights": 136,
      "occupancy": 81.0,
      "revpar": 322
    },
    {
      "month": "Mar '26",
      "gross": 57274,
      "toOwner": 51649,
      "bookings": 46,
      "adr": 401,
      "nights": 143,
      "occupancy": 76.9,
      "revpar": 308
    },
    {
      "month": "Apr '26",
      "gross": 36619,
      "toOwner": 32163,
      "bookings": 30,
      "adr": 482,
      "nights": 76,
      "occupancy": 42.2,
      "revpar": 203
    },
    {
      "month": "May '26",
      "gross": 28263,
      "toOwner": 24924,
      "bookings": 19,
      "adr": 449,
      "nights": 63,
      "occupancy": 33.9,
      "revpar": 152
    },
    {
      "month": "Jun '26",
      "gross": 13428,
      "toOwner": 11998,
      "bookings": 9,
      "adr": 480,
      "nights": 28,
      "occupancy": 15.6,
      "revpar": 75
    },
    {
      "month": "Jul '26",
      "gross": 3799,
      "toOwner": 3282,
      "bookings": 3,
      "adr": 422,
      "nights": 9,
      "occupancy": 4.8,
      "revpar": 20
    },
    {
      "month": "Aug '26",
      "gross": 2967,
      "toOwner": 2564,
      "bookings": 2,
      "adr": 424,
      "nights": 7,
      "occupancy": 3.8,
      "revpar": 16
    },
    {
      "month": "Sep '26",
      "gross": 5184,
      "toOwner": 4700,
      "bookings": 4,
      "adr": 432,
      "nights": 12,
      "occupancy": 6.7,
      "revpar": 29
    },
    {
      "month": "Oct '26",
      "gross": 3441,
      "toOwner": 2973,
      "bookings": 3,
      "adr": 382,
      "nights": 9,
      "occupancy": 4.8,
      "revpar": 18
    },
    {
      "month": "Nov '26",
      "gross": 1204,
      "toOwner": 1041,
      "bookings": 1,
      "adr": 401,
      "nights": 3,
      "occupancy": 1.7,
      "revpar": 7
    },
    {
      "month": "Dec '26",
      "gross": 3729,
      "toOwner": 3356,
      "bookings": 3,
      "adr": 339,
      "nights": 11,
      "occupancy": 5.9,
      "revpar": 20
    }
  ],
  "sourceData": [
    {
      "name": "Airbnb",
      "bookings": 160,
      "pct": 62.7,
      "revenue": 184798
    },
    {
      "name": "Expedia",
      "bookings": 46,
      "pct": 18.0,
      "revenue": 45938
    },
    {
      "name": "Booking.com",
      "bookings": 25,
      "pct": 9.8,
      "revenue": 20043
    },
    {
      "name": "Direct",
      "bookings": 13,
      "pct": 5.1,
      "revenue": 13458
    },
    {
      "name": "ZenStay",
      "bookings": 8,
      "pct": 3.1,
      "revenue": 7846
    },
    {
      "name": "Vrbo",
      "bookings": 1,
      "pct": 0.4,
      "revenue": 626
    },
    {
      "name": "VHR",
      "bookings": 1,
      "pct": 0.4,
      "revenue": 0
    },
    {
      "name": "owner",
      "bookings": 1,
      "pct": 0.4,
      "revenue": 0
    }
  ],
  "unitData": [
    {
      "unit": "1",
      "bookings": 56,
      "toOwner": 53897,
      "avgRev": 962,
      "adr": 360,
      "nights": 168,
      "avgStay": 3.0
    },
    {
      "unit": "2",
      "bookings": 37,
      "toOwner": 51230,
      "avgRev": 1385,
      "adr": 571,
      "nights": 98,
      "avgStay": 2.6
    },
    {
      "unit": "3",
      "bookings": 36,
      "toOwner": 31674,
      "avgRev": 880,
      "adr": 356,
      "nights": 99,
      "avgStay": 2.8
    },
    {
      "unit": "4",
      "bookings": 40,
      "toOwner": 31539,
      "avgRev": 788,
      "adr": 343,
      "nights": 101,
      "avgStay": 2.5
    },
    {
      "unit": "5",
      "bookings": 48,
      "toOwner": 44981,
      "avgRev": 937,
      "adr": 388,
      "nights": 133,
      "avgStay": 2.8
    },
    {
      "unit": "6",
      "bookings": 38,
      "toOwner": 30477,
      "avgRev": 802,
      "adr": 370,
      "nights": 94,
      "avgStay": 2.5
    }
  ],
  "expenseCategories": [
    {
      "category": "Cleaning",
      "amount": 12853,
      "pct": 26.3
    },
    {
      "category": "Supplies",
      "amount": 10139,
      "pct": 20.7
    },
    {
      "category": "Management",
      "amount": 8134,
      "pct": 16.6
    },
    {
      "category": "Taxes & Licenses",
      "amount": 7388,
      "pct": 15.1
    },
    {
      "category": "CapEx",
      "amount": 5959,
      "pct": 12.2
    },
    {
      "category": "Marketing",
      "amount": 2410,
      "pct": 4.9
    },
    {
      "category": "Maintenance",
      "amount": 857,
      "pct": 1.8
    },
    {
      "category": "OTA Reconciliation",
      "amount": 746,
      "pct": 1.5
    },
    {
      "category": "Guest Credits",
      "amount": 214,
      "pct": 0.4
    },
    {
      "category": "Other",
      "amount": 199,
      "pct": 0.4
    }
  ],
  "expenseMonthly": [
    {
      "month": "Dec '25",
      "total": 6916,
      "cleaning": 0,
      "supplies": 3647,
      "capex": 2928,
      "maint": 0,
      "marketing": 0,
      "other": 342
    },
    {
      "month": "Jan '26",
      "total": 26905,
      "cleaning": 8483,
      "supplies": 6140,
      "capex": 2966,
      "maint": 572,
      "marketing": 2410,
      "other": 6334
    },
    {
      "month": "Feb '26",
      "total": 15078,
      "cleaning": 4370,
      "supplies": 352,
      "capex": 66,
      "maint": 285,
      "marketing": 0,
      "other": 10006
    }
  ],
  "topVendors": [
    {
      "vendor": "Spring Cleaning (Quentin & Kayli Keiser)",
      "amount": 12853,
      "category": "Cleaning"
    },
    {
      "vendor": "Zenstay Inc",
      "amount": 8607,
      "category": "Management"
    },
    {
      "vendor": "City of Santa Barbara (Business License Tax Application) (Business License Tax Application) (Business License Tax Application) (Business License Tax Application)",
      "amount": 7388,
      "category": "Taxes & Licenses"
    },
    {
      "vendor": "Amazon (Amazon) (Amazon) (Amazon)",
      "amount": 5785,
      "category": "Supplies"
    },
    {
      "vendor": "MAJESTIC METALS (Majestic Metals)",
      "amount": 2738,
      "category": "CapEx"
    },
    {
      "vendor": "Tripadvisor (Tripadvisor) (Tripadvisor) (Tripadvisor)",
      "amount": 2400,
      "category": "Marketing"
    },
    {
      "vendor": "Skiview Productions (Juan C Lopez Romero)",
      "amount": 2175,
      "category": "CapEx"
    },
    {
      "vendor": "Costco (Costco) (Costco)",
      "amount": 2087,
      "category": "Supplies"
    },
    {
      "vendor": "Public Goods (Public Goods) (Public Goods)",
      "amount": 1140,
      "category": "Supplies"
    },
    {
      "vendor": "California Design Den (California Design Den)",
      "amount": 1052,
      "category": "Supplies"
    }
  ],
  "sbCompData": [
    {
      "metric": "ADR",
      "casaYano": 394,
      "sbMedian": 321,
      "sbTop25": 521
    },
    {
      "metric": "Owner Margin",
      "casaYano": 89.4,
      "sbMedian": 75,
      "sbTop25": 85
    },
    {
      "metric": "OTA Commission %",
      "casaYano": 10.1,
      "sbMedian": 15,
      "sbTop25": 12
    }
  ],
  "actualsVsPf": [
    {
      "month": "Jan",
      "pfGross": 40041,
      "actualGross": 40041,
      "bookedGross": 0,
      "variance": 0,
      "variancePct": 0.0,
      "status": "closed"
    },
    {
      "month": "Feb",
      "pfGross": 52466,
      "actualGross": 54065,
      "bookedGross": 0,
      "variance": 1599,
      "variancePct": 3.0,
      "status": "closed"
    },
    {
      "month": "Mar",
      "pfGross": 56953,
      "actualGross": 0,
      "bookedGross": 57274,
      "variance": null,
      "variancePct": null,
      "status": "current"
    },
    {
      "month": "Apr",
      "pfGross": 57375,
      "actualGross": 0,
      "bookedGross": 36619,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "May",
      "pfGross": 58590,
      "actualGross": 0,
      "bookedGross": 28263,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Jun",
      "pfGross": 69120,
      "actualGross": 0,
      "bookedGross": 13428,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Jul",
      "pfGross": 76260,
      "actualGross": 0,
      "bookedGross": 3799,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Aug",
      "pfGross": 71424,
      "actualGross": 0,
      "bookedGross": 2967,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Sep",
      "pfGross": 45900,
      "actualGross": 0,
      "bookedGross": 5184,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Oct",
      "pfGross": 45338,
      "actualGross": 0,
      "bookedGross": 3441,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Nov",
      "pfGross": 48510,
      "actualGross": 0,
      "bookedGross": 1204,
      "variance": null,
      "variancePct": null,
      "status": "future"
    },
    {
      "month": "Dec",
      "pfGross": 54405,
      "actualGross": 0,
      "bookedGross": 3729,
      "variance": null,
      "variancePct": null,
      "status": "future"
    }
  ],
  "cumulativeTrajectory": [
    {
      "month": "Jan",
      "actualCumulative": 40041,
      "pfCumulative": 40041
    },
    {
      "month": "Feb",
      "actualCumulative": 94106,
      "pfCumulative": 92507
    },
    {
      "month": "Mar",
      "actualCumulative": 151380,
      "pfCumulative": 149460
    },
    {
      "month": "Apr",
      "actualCumulative": 151380,
      "pfCumulative": 206835
    },
    {
      "month": "May",
      "actualCumulative": 151380,
      "pfCumulative": 265425
    },
    {
      "month": "Jun",
      "actualCumulative": 151380,
      "pfCumulative": 334545
    },
    {
      "month": "Jul",
      "actualCumulative": 151380,
      "pfCumulative": 410805
    },
    {
      "month": "Aug",
      "actualCumulative": 151380,
      "pfCumulative": 482229
    },
    {
      "month": "Sep",
      "actualCumulative": 151380,
      "pfCumulative": 528129
    },
    {
      "month": "Oct",
      "actualCumulative": 151380,
      "pfCumulative": 573467
    },
    {
      "month": "Nov",
      "actualCumulative": 151380,
      "pfCumulative": 621977
    },
    {
      "month": "Dec",
      "actualCumulative": 151380,
      "pfCumulative": 676382
    }
  ],
  "forwardPace": [
    {
      "month": "Mar",
      "pfGross": 56953,
      "bookedGross": 57274,
      "pacePct": 100.6
    },
    {
      "month": "Apr",
      "pfGross": 57375,
      "bookedGross": 36619,
      "pacePct": 63.8
    },
    {
      "month": "May",
      "pfGross": 58590,
      "bookedGross": 28263,
      "pacePct": 48.2
    },
    {
      "month": "Jun",
      "pfGross": 69120,
      "bookedGross": 13428,
      "pacePct": 19.4
    },
    {
      "month": "Jul",
      "pfGross": 76260,
      "bookedGross": 3799,
      "pacePct": 5.0
    },
    {
      "month": "Aug",
      "pfGross": 71424,
      "bookedGross": 2967,
      "pacePct": 4.2
    },
    {
      "month": "Sep",
      "pfGross": 45900,
      "bookedGross": 5184,
      "pacePct": 11.3
    },
    {
      "month": "Oct",
      "pfGross": 45338,
      "bookedGross": 3441,
      "pacePct": 7.6
    },
    {
      "month": "Nov",
      "pfGross": 48510,
      "bookedGross": 1204,
      "pacePct": 2.5
    },
    {
      "month": "Dec",
      "pfGross": 54405,
      "bookedGross": 3729,
      "pacePct": 6.9
    }
  ],
  "blendedForecast": [
    {
      "month": "Jan",
      "gross": 40041,
      "netOwner": 35785,
      "adr": 286,
      "occ": 75.3,
      "opex": 11000,
      "noi": 24785,
      "source": "actual"
    },
    {
      "month": "Feb",
      "gross": 54065,
      "netOwner": 48880,
      "adr": 398,
      "occ": 81.0,
      "opex": 8500,
      "noi": 40380,
      "source": "actual"
    },
    {
      "month": "Mar",
      "gross": 56953,
      "netOwner": 50929,
      "adr": 392,
      "occ": 78,
      "opex": 8000,
      "noi": 42929,
      "source": "projected"
    },
    {
      "month": "Apr",
      "gross": 57375,
      "netOwner": 51295,
      "adr": 425,
      "occ": 75,
      "opex": 7500,
      "noi": 43795,
      "source": "projected"
    },
    {
      "month": "May",
      "gross": 58590,
      "netOwner": 52382,
      "adr": 420,
      "occ": 75,
      "opex": 7500,
      "noi": 44882,
      "source": "projected"
    },
    {
      "month": "Jun",
      "gross": 69120,
      "netOwner": 61775,
      "adr": 480,
      "occ": 80,
      "opex": 7000,
      "noi": 54775,
      "source": "projected"
    },
    {
      "month": "Jul",
      "gross": 76260,
      "netOwner": 68169,
      "adr": 500,
      "occ": 82,
      "opex": 7000,
      "noi": 61169,
      "source": "projected"
    },
    {
      "month": "Aug",
      "gross": 71424,
      "netOwner": 63853,
      "adr": 480,
      "occ": 80,
      "opex": 7000,
      "noi": 56853,
      "source": "projected"
    },
    {
      "month": "Sep",
      "gross": 45900,
      "netOwner": 41035,
      "adr": 375,
      "occ": 68,
      "opex": 7500,
      "noi": 33535,
      "source": "projected"
    },
    {
      "month": "Oct",
      "gross": 45338,
      "netOwner": 40532,
      "adr": 375,
      "occ": 65,
      "opex": 7500,
      "noi": 33032,
      "source": "projected"
    },
    {
      "month": "Nov",
      "gross": 48510,
      "netOwner": 43368,
      "adr": 385,
      "occ": 70,
      "opex": 7500,
      "noi": 35868,
      "source": "projected"
    },
    {
      "month": "Dec",
      "gross": 54405,
      "netOwner": 48638,
      "adr": 390,
      "occ": 75,
      "opex": 8000,
      "noi": 40638,
      "source": "projected"
    }
  ],
  "blendedTotals": {
    "gross": 677981,
    "netOwner": 606641,
    "opex": 94000,
    "mgmtFee": 67798,
    "noiBeforeFixed": 512641,
    "noiAfterKnown": 380664
  },
  "proForma": {
    "monthly": [
      {
        "month": "Jan",
        "adr": 286,
        "occ": 75,
        "gross": 40041,
        "netOwner": 35785,
        "opex": 11000,
        "noi": 24785,
        "bookings": 56
      },
      {
        "month": "Feb",
        "adr": 397,
        "occ": 79,
        "gross": 52466,
        "netOwner": 47423,
        "opex": 8500,
        "noi": 38923,
        "bookings": 53
      },
      {
        "month": "Mar",
        "adr": 392,
        "occ": 78,
        "gross": 56953,
        "netOwner": 50929,
        "opex": 8000,
        "noi": 42929,
        "bookings": 38
      },
      {
        "month": "Apr",
        "adr": 425,
        "occ": 75,
        "gross": 57375,
        "netOwner": 51295,
        "opex": 7500,
        "noi": 43795,
        "bookings": 35
      },
      {
        "month": "May",
        "adr": 420,
        "occ": 75,
        "gross": 58590,
        "netOwner": 52382,
        "opex": 7500,
        "noi": 44882,
        "bookings": 36
      },
      {
        "month": "Jun",
        "adr": 480,
        "occ": 80,
        "gross": 69120,
        "netOwner": 61775,
        "opex": 7000,
        "noi": 54775,
        "bookings": 40
      },
      {
        "month": "Jul",
        "adr": 500,
        "occ": 82,
        "gross": 76260,
        "netOwner": 68169,
        "opex": 7000,
        "noi": 61169,
        "bookings": 44
      },
      {
        "month": "Aug",
        "adr": 480,
        "occ": 80,
        "gross": 71424,
        "netOwner": 63853,
        "opex": 7000,
        "noi": 56853,
        "bookings": 42
      },
      {
        "month": "Sep",
        "adr": 375,
        "occ": 68,
        "gross": 45900,
        "netOwner": 41035,
        "opex": 7500,
        "noi": 33535,
        "bookings": 32
      },
      {
        "month": "Oct",
        "adr": 375,
        "occ": 65,
        "gross": 45338,
        "netOwner": 40532,
        "opex": 7500,
        "noi": 33032,
        "bookings": 30
      },
      {
        "month": "Nov",
        "adr": 385,
        "occ": 70,
        "gross": 48510,
        "netOwner": 43368,
        "opex": 7500,
        "noi": 35868,
        "bookings": 33
      },
      {
        "month": "Dec",
        "adr": 390,
        "occ": 75,
        "gross": 54405,
        "netOwner": 48638,
        "opex": 8000,
        "noi": 40638,
        "bookings": 37
      }
    ],
    "waterfall": [
      {
        "name": "Gross Revenue",
        "value": 676382,
        "type": "positive"
      },
      {
        "name": "OTA Commissions",
        "value": -68517,
        "type": "negative"
      },
      {
        "name": "Taxes (TOT)",
        "value": -81166,
        "type": "negative"
      },
      {
        "name": "Processing",
        "value": -16910,
        "type": "negative"
      },
      {
        "name": "Net to Owner",
        "value": 605184,
        "type": "subtotal"
      },
      {
        "name": "Cleaning",
        "value": -78020,
        "type": "opex"
      },
      {
        "name": "Supplies/Maint",
        "value": -13160,
        "type": "opex"
      },
      {
        "name": "Other OpEx",
        "value": -2820,
        "type": "opex"
      },
      {
        "name": "Mgmt Fee (10%)",
        "value": -67638,
        "type": "mgmt"
      },
      {
        "name": "Property Tax",
        "value": -26679,
        "type": "opex"
      },
      {
        "name": "Insurance",
        "value": -13500,
        "type": "opex"
      },
      {
        "name": "Other Fixed (6 items)",
        "value": -24000,
        "type": "opex"
      },
      {
        "name": "NOI (excl. remaining TBD)",
        "value": 379367,
        "type": "total"
      }
    ],
    "gross": 676382,
    "netOwner": 605184,
    "opex": 94000,
    "mgmtFee": 67638,
    "propertyTax": 26679,
    "insurance": 13500,
    "otherFixed": 24000,
    "noiBeforeFixed": 511184,
    "noiAfterKnown": 379367,
    "avgOcc": 75.2,
    "avgAdr": 409,
    "mgmtFeePct": 0.1
  },
  "config": {
    "mgmtFeePct": 0.1,
    "propertyTaxAnnual": 26679,
    "insuranceAnnual": 13500,
    "sbMedianAdr": 321,
    "sbTop25Adr": 521
  }
};
