// Auto-generated by build.py — do not edit manually
// Generated: 2026-02-11T00:51:45.344104
window.__DATA__ = {
  "generatedAt": "2026-02-11T00:51:45.344104",
  "openingDate": "2025-12-18",
  "daysSinceLaunch": 55,
  "numUnits": 6,
  "summary": {
    "totalBookings": 172,
    "totalGross": 172777,
    "totalToOwner": 154921,
    "blendedAdr": 368,
    "ownerMargin": 89.7,
    "otaPct": 9.7,
    "avgStay": 2.7,
    "avgLeadTime": 35,
    "totalNights": 470,
    "totalExpenses": 39334,
    "otaBookingPct": 94.2,
    "directBookings": 10,
    "repeatGuestPct": 0,
    "costPerTurn": 115
  },
  "monthlyData": [
    {
      "month": "Dec '25",
      "gross": 22695,
      "toOwner": 20483,
      "bookings": 24,
      "adr": 405
    },
    {
      "month": "Jan '26",
      "gross": 40041,
      "toOwner": 35785,
      "bookings": 56,
      "adr": 286
    },
    {
      "month": "Feb '26",
      "gross": 47248,
      "toOwner": 42279,
      "bookings": 46,
      "adr": 387
    },
    {
      "month": "Mar '26",
      "gross": 26757,
      "toOwner": 24303,
      "bookings": 19,
      "adr": 377
    },
    {
      "month": "Apr '26",
      "gross": 12377,
      "toOwner": 10695,
      "bookings": 9,
      "adr": 495
    },
    {
      "month": "May '26",
      "gross": 8830,
      "toOwner": 7969,
      "bookings": 8,
      "adr": 401
    },
    {
      "month": "Jun '26",
      "gross": 8428,
      "toOwner": 7871,
      "bookings": 5,
      "adr": 496
    },
    {
      "month": "Jul '26",
      "gross": 2602,
      "toOwner": 2254,
      "bookings": 2,
      "adr": 434
    },
    {
      "month": "Oct '26",
      "gross": 1319,
      "toOwner": 1140,
      "bookings": 1,
      "adr": 330
    },
    {
      "month": "Nov '26",
      "gross": 1204,
      "toOwner": 1041,
      "bookings": 1,
      "adr": 401
    },
    {
      "month": "Dec '26",
      "gross": 1275,
      "toOwner": 1102,
      "bookings": 1,
      "adr": 319
    }
  ],
  "sourceData": [
    {
      "name": "Airbnb",
      "bookings": 96,
      "pct": 55.8,
      "revenue": 107921
    },
    {
      "name": "Expedia",
      "bookings": 36,
      "pct": 20.9,
      "revenue": 31977
    },
    {
      "name": "Booking.com",
      "bookings": 21,
      "pct": 12.2,
      "revenue": 18118
    },
    {
      "name": "Direct",
      "bookings": 10,
      "pct": 5.8,
      "revenue": 9243
    },
    {
      "name": "ZenStay",
      "bookings": 7,
      "pct": 4.1,
      "revenue": 5518
    },
    {
      "name": "VHR",
      "bookings": 1,
      "pct": 0.6,
      "revenue": 0
    },
    {
      "name": "owner",
      "bookings": 1,
      "pct": 0.6,
      "revenue": 0
    }
  ],
  "unitData": [
    {
      "unit": "1",
      "bookings": 27,
      "toOwner": 28717,
      "avgRev": 1064,
      "adr": 329,
      "nights": 95,
      "avgStay": 3.5
    },
    {
      "unit": "2",
      "bookings": 25,
      "toOwner": 28099,
      "avgRev": 1124,
      "adr": 551,
      "nights": 56,
      "avgStay": 2.2
    },
    {
      "unit": "3",
      "bookings": 25,
      "toOwner": 18198,
      "avgRev": 728,
      "adr": 314,
      "nights": 64,
      "avgStay": 2.6
    },
    {
      "unit": "4",
      "bookings": 30,
      "toOwner": 24066,
      "avgRev": 802,
      "adr": 324,
      "nights": 81,
      "avgStay": 2.7
    },
    {
      "unit": "5",
      "bookings": 39,
      "toOwner": 35479,
      "avgRev": 910,
      "adr": 376,
      "nights": 109,
      "avgStay": 2.8
    },
    {
      "unit": "6",
      "bookings": 26,
      "toOwner": 20362,
      "avgRev": 783,
      "adr": 358,
      "nights": 65,
      "avgStay": 2.5
    }
  ],
  "expenseCategories": [
    {
      "category": "Cleaning",
      "amount": 11543,
      "pct": 29.3
    },
    {
      "category": "Supplies",
      "amount": 10495,
      "pct": 26.7
    },
    {
      "category": "Taxes & Licenses",
      "amount": 7388,
      "pct": 18.8
    },
    {
      "category": "CapEx",
      "amount": 5959,
      "pct": 15.2
    },
    {
      "category": "Marketing",
      "amount": 2410,
      "pct": 6.1
    },
    {
      "category": "Maintenance",
      "amount": 852,
      "pct": 2.2
    },
    {
      "category": "Other",
      "amount": 687,
      "pct": 1.7
    }
  ],
  "expenseMonthly": [
    {
      "month": "Dec '25",
      "total": 8713,
      "cleaning": 0,
      "supplies": 5505,
      "capex": 2928,
      "maint": 280,
      "marketing": 0,
      "other": 0
    },
    {
      "month": "Jan '26",
      "total": 21454,
      "cleaning": 8483,
      "supplies": 4918,
      "capex": 2966,
      "maint": 572,
      "marketing": 2410,
      "other": 2105
    },
    {
      "month": "Feb '26",
      "total": 9167,
      "cleaning": 3060,
      "supplies": 72,
      "capex": 66,
      "maint": 0,
      "marketing": 0,
      "other": 5970
    }
  ],
  "topVendors": [
    {
      "vendor": "Spring Cleaning (Quentin & Kayli Keiser)",
      "amount": 11543,
      "category": "Cleaning"
    },
    {
      "vendor": "City of Santa Barbara (Business License Tax Application) (Business License Tax Application) (Business License Tax Application) (Business License Tax Application)",
      "amount": 7388,
      "category": "Taxes & Licenses"
    },
    {
      "vendor": "Amazon (Amazon) (Amazon) (Amazon)",
      "amount": 6421,
      "category": "Supplies"
    },
    {
      "vendor": "MAJESTIC METALS (Majestic Metals)",
      "amount": 2738,
      "category": "CapEx"
    },
    {
      "vendor": "Tripadvisor (Tripadvisor) (Tripadvisor) (Tripadvisor)",
      "amount": 2400,
      "category": "Marketing"
    },
    {
      "vendor": "Skiview Productions (Juan C Lopez Romero)",
      "amount": 2175,
      "category": "CapEx"
    },
    {
      "vendor": "Costco (Costco) (Costco)",
      "amount": 2087,
      "category": "Supplies"
    },
    {
      "vendor": "Public Goods (Public Goods) (Public Goods)",
      "amount": 1140,
      "category": "Supplies"
    },
    {
      "vendor": "California Design Den (California Design Den)",
      "amount": 1052,
      "category": "Supplies"
    },
    {
      "vendor": "Martin Hernandez Painting (Christian Hernandez) (Christian Hernandez)",
      "amount": 832,
      "category": "CapEx"
    }
  ],
  "sbCompData": [
    {
      "metric": "ADR",
      "casaYano": 368,
      "sbMedian": 321,
      "sbTop25": 521
    },
    {
      "metric": "Owner Margin",
      "casaYano": 89.7,
      "sbMedian": 75,
      "sbTop25": 85
    },
    {
      "metric": "OTA Commission %",
      "casaYano": 9.7,
      "sbMedian": 15,
      "sbTop25": 12
    }
  ],
  "proForma": {
    "monthly": [
      {
        "month": "Jan",
        "adr": 375,
        "occ": 82,
        "gross": 67350,
        "netOwner": 56076,
        "opex": 9500,
        "noi": 46576,
        "bookings": 57
      },
      {
        "month": "Feb",
        "adr": 400,
        "occ": 80,
        "gross": 62350,
        "netOwner": 51829,
        "opex": 6870,
        "noi": 44959,
        "bookings": 50
      },
      {
        "month": "Mar",
        "adr": 425,
        "occ": 78,
        "gross": 71075,
        "netOwner": 58995,
        "opex": 7314,
        "noi": 51681,
        "bookings": 54
      },
      {
        "month": "Apr",
        "adr": 425,
        "occ": 80,
        "gross": 70475,
        "netOwner": 58481,
        "opex": 7203,
        "noi": 51278,
        "bookings": 53
      },
      {
        "month": "May",
        "adr": 450,
        "occ": 78,
        "gross": 74700,
        "netOwner": 61923,
        "opex": 7314,
        "noi": 54609,
        "bookings": 54
      },
      {
        "month": "Jun",
        "adr": 525,
        "occ": 85,
        "gross": 90300,
        "netOwner": 74615,
        "opex": 7647,
        "noi": 66968,
        "bookings": 57
      },
      {
        "month": "Jul",
        "adr": 550,
        "occ": 85,
        "gross": 97225,
        "netOwner": 80267,
        "opex": 7869,
        "noi": 72398,
        "bookings": 59
      },
      {
        "month": "Aug",
        "adr": 525,
        "occ": 82,
        "gross": 90300,
        "netOwner": 74615,
        "opex": 7647,
        "noi": 66968,
        "bookings": 57
      },
      {
        "month": "Sep",
        "adr": 350,
        "occ": 72,
        "gross": 53900,
        "netOwner": 44947,
        "opex": 6648,
        "noi": 38299,
        "bookings": 48
      },
      {
        "month": "Oct",
        "adr": 350,
        "occ": 70,
        "gross": 53900,
        "netOwner": 44947,
        "opex": 6648,
        "noi": 38299,
        "bookings": 48
      },
      {
        "month": "Nov",
        "adr": 375,
        "occ": 75,
        "gross": 59375,
        "netOwner": 49428,
        "opex": 6870,
        "noi": 42558,
        "bookings": 50
      },
      {
        "month": "Dec",
        "adr": 375,
        "occ": 80,
        "gross": 65500,
        "netOwner": 54522,
        "opex": 7425,
        "noi": 47097,
        "bookings": 55
      }
    ],
    "waterfall": [
      {
        "name": "Gross Revenue",
        "value": 856450,
        "type": "positive"
      },
      {
        "name": "OTA Commissions",
        "value": -82909,
        "type": "negative"
      },
      {
        "name": "Taxes (TOT)",
        "value": -102774,
        "type": "negative"
      },
      {
        "name": "Processing",
        "value": -21411,
        "type": "negative"
      },
      {
        "name": "Net to Owner",
        "value": 710645,
        "type": "subtotal"
      },
      {
        "name": "Cleaning",
        "value": -73833,
        "type": "opex"
      },
      {
        "name": "Supplies/Maint",
        "value": -12454,
        "type": "opex"
      },
      {
        "name": "Other OpEx",
        "value": -2669,
        "type": "opex"
      },
      {
        "name": "Mgmt Fee (10%)",
        "value": -85645,
        "type": "mgmt"
      },
      {
        "name": "Property Tax",
        "value": -26679,
        "type": "opex"
      },
      {
        "name": "Insurance",
        "value": -13500,
        "type": "opex"
      },
      {
        "name": "Other Fixed (6 items)",
        "value": -24000,
        "type": "opex"
      },
      {
        "name": "NOI (excl. remaining TBD)",
        "value": 471866,
        "type": "total"
      }
    ],
    "gross": 856450,
    "netOwner": 710645,
    "opex": 88955,
    "mgmtFee": 85645,
    "propertyTax": 26679,
    "insurance": 13500,
    "otherFixed": 24000,
    "noiBeforeFixed": 621690,
    "noiAfterKnown": 471866,
    "avgOcc": 78.9,
    "avgAdr": 427,
    "mgmtFeePct": 0.1
  },
  "config": {
    "mgmtFeePct": 0.1,
    "propertyTaxAnnual": 26679,
    "insuranceAnnual": 13500,
    "sbMedianAdr": 321,
    "sbTop25Adr": 521
  }
};
